angular.module('TripUserPageModules',['ui.router'])
	.config(function($stateProvider,$urlRouterProvider){
		$stateProvider.state('tripUserPage',{
			url:'/tripUserPage',
			templateUrl:'./modules/tripUserPage/tripUserPage.html',
			controller:'TripUserPageCtrl',
			css:'./modules/tripUserPage/tripUserPage.css'
		})
	})
	.controller('TripUserPageCtrl',['$scope','$http',function($scope,$http){
		$scope.tripuPage_inputClick = function(){
        	$("#common_nav").removeClass().addClass("common_show");
        	$(".container").removeClass("container_hide").addClass("container_show");
        	$(".container").off();
	        $(".container").on("click",function(){
        		if($("#common_nav").css("opacity")=="1"){
	        		$("#common_nav").removeClass().addClass("common_hide");
	        		$(".container").removeClass("container_show").addClass("container_hide");
        		}
	        })
        }
	}])
